name: cw_3
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - lib/assets/dog.png
    - lib/assets/happy.png
    - lib/assets/sad.png
    - lib/assets/angry.png

  uses-material-design: true
